application: dotmatrix
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /html
  static_dir: html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: dotmatrix.py
