application: simpleajax
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /html
  static_dir: html
- url: /js
  static_dir: js
- url: /.*
  script: devchat.py
